# This file was generated by GoReleaser. DO NOT EDIT.
class Forward < Formula
  desc "Extended kubectl port-forward - multiple port forwarding simultaneously."
  homepage "https://github.com/kamilsk/forward"
  url "https://github.com/kamilsk/forward/releases/download/0.2.1/forward_0.2.1_macOS-64bit.tar.gz"
  version "0.2.1"
  sha256 "6eb16e4c337c8260adb649e9081ad9ebf52c4556b120019fdd6cf79514060a11"

  def install
    bin.install "forward"
  end

  def caveats; <<~EOS
    Use `forward pod [local:]remote`
  EOS
  end
end
