# This file was generated by GoReleaser. DO NOT EDIT.
class Forward < Formula
  desc "Extended kubectl port-forward - reliable multiple port forwarding."
  homepage "https://github.com/kamilsk/forward"
  version "0.5.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kamilsk/forward/releases/download/0.5.3/forward_0.5.3_macOS-64bit.tar.gz"
    sha256 "1825a56f3bc270ec9f0b5390af15d74b8bae5782fabc9ff8d695dc7e966bb4da"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kamilsk/forward/releases/download/0.5.3/forward_0.5.3_Linux-64bit.tar.gz"
      sha256 "7607e276f530b9468ff72af32e29131fe499b3c099e4ddf792d0d329ebc84f5b"
    end
  end

  def install
    bin.install "forward"
  end

  def caveats; <<~EOS
    Use `forward pod [local:]remote`
  EOS
  end
end
