# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goimports < Formula
  desc "Command goimports updates your Go import lines,
adding missing ones and removing unreferenced ones.
In addition to fixing imports, goimports also formats
your code in the same style as gofmt so it can be used
as a replacement for your editor's gofmt-on-save hook.
"
  homepage "https://github.com/kamilsk/go-tools"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kamilsk/go-tools/releases/download/v0.1.0/goimports_0.1.0_macOS-64bit.tar.gz"
    sha256 "278ea81b593b7cf89422993a28d31529eec44b43156bd836852e433cfb124d09"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/kamilsk/go-tools/releases/download/v0.1.0/goimports_0.1.0_Linux-64bit.tar.gz"
    sha256 "4d5bbeba8eac9a72bece45825ad0f7aa1298de308b5ef7ea0ced4a83f8cf46ed"
  end

  def install
    bin.install "goimports"
    prefix.install_metafiles
  end

  test do
    system "#{bin}/goimports -help"
  end
end
