# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GolangciLint < Formula
  desc "golangci-lint is a fast Go linters runner. It runs linters in parallel,
uses caching, supports yaml config, has integrations with all major IDE
and has dozens of linters included.
"
  homepage "https://github.com/kamilsk/golangci-lint"
  version "1.41.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kamilsk/golangci-lint/releases/download/v1.41.1/golangci-lint_1.41.1_macOS-64bit.tar.gz"
      sha256 "3285cc0aacd46103fefb55ded7c198bcf66aa1136bffae5a19d45b7d42f28a80"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kamilsk/golangci-lint/releases/download/v1.41.1/golangci-lint_1.41.1_Linux-64bit.tar.gz"
      sha256 "657560f047324a07776a9727a45551ac46ac401eb96086de4e725f98734e78f6"
    end
  end

  def install
    bin.install "golangci-lint"
    prefix.install_metafiles
  end

  test do
    system "#{bin}/golangci-lint help"
  end
end
