# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GolangciLint < Formula
  desc "golangci-lint is a fast Go linters runner. It runs linters in parallel,
uses caching, supports yaml config, has integrations with all major IDE
and has dozens of linters included.
"
  homepage "https://github.com/kamilsk/golangci-lint"
  version "1.41.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kamilsk/golangci-lint/releases/download/v1.41.0/golangci-lint_1.41.0_macOS-64bit.tar.gz"
      sha256 "543fded2456453d1cc7d7a5e5fc2ea55ed7a521ae500576290c4de13b8812ebb"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kamilsk/golangci-lint/releases/download/v1.41.0/golangci-lint_1.41.0_Linux-64bit.tar.gz"
      sha256 "58b9a7d764e49e1947e52c770222d9217fc79400faaa002f589e3ba02b7de8c3"
    end
  end

  def install
    bin.install "golangci-lint"
    prefix.install_metafiles
  end

  test do
    system "#{bin}/golangci-lint help"
  end
end
