# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GolangciLint < Formula
  desc "golangci-lint is a fast Go linters runner. It runs linters in parallel,
uses caching, supports yaml config, has integrations with all major IDE
and has dozens of linters included.
"
  homepage "https://github.com/kamilsk/golangci-lint"
  version "1.40.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/kamilsk/golangci-lint/releases/download/v1.40.1/golangci-lint_1.40.1_macOS-64bit.tar.gz"
    sha256 "dacb98a884242edadc11d0d5f3f4079ce41e0da34be3af0726d4875853207833"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/kamilsk/golangci-lint/releases/download/v1.40.1/golangci-lint_1.40.1_Linux-64bit.tar.gz"
    sha256 "f4689e03e825ed7933a8b8629ab7d2f863ba34c4f191270f44b54c751f47aa31"
  end

  def install
    bin.install "golangci-lint"
    prefix.install_metafiles
  end

  test do
    system "#{bin}/golangci-lint help"
  end
end
