# This file was generated by GoReleaser. DO NOT EDIT.
class Grafaman < Formula
  desc "Metrics coverage reporter for Graphite and Grafana."
  homepage "https://github.com/kamilsk/grafaman"
  version "0.5.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kamilsk/grafaman/releases/download/v0.5.0/grafaman_0.5.0_macOS-64bit.tar.gz"
    sha256 "786539ce1449b1158aa4b5f6268d676d938a6f12dd8cb6dcb420f36f6b151469"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kamilsk/grafaman/releases/download/v0.5.0/grafaman_0.5.0_Linux-64bit.tar.gz"
      sha256 "5b28143f9ac5b6c1bd28cfa5e0c1d8716cb61143c7096f8ccbf9cad2e85166f6"
    end
  end

  def install
    bin.install "grafaman"
    output = Utils.popen_read("#{bin}/grafaman completion bash")
    (bash_completion/"grafaman").write output
    output = Utils.popen_read("#{bin}/grafaman completion zsh")
    (zsh_completion/"_grafaman").write output
    prefix.install_metafiles
  end

  test do
    system "#{bin}/grafaman --version"
  end
end
