# This file was generated by GoReleaser. DO NOT EDIT.
class Grafaman < Formula
  desc "Metrics coverage reporter for Graphite and Grafana."
  homepage "https://github.com/kamilsk/grafaman"
  version "1.0.0-beta2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kamilsk/grafaman/releases/download/v1.0.0-beta2/grafaman_1.0.0-beta2_macOS-64bit.tar.gz"
    sha256 "d324ba1c661259357f44808646e5092bb034695cf291fcaa05656589660c794e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kamilsk/grafaman/releases/download/v1.0.0-beta2/grafaman_1.0.0-beta2_Linux-64bit.tar.gz"
      sha256 "425625d7e4663aec1ccb98669384fa1a2e25b9c4c734821b584b416bf2a4e239"
    end
  end

  def install
    bin.install "grafaman"
    output = Utils.popen_read("#{bin}/grafaman completion bash")
    (bash_completion/grafaman).write output
    output = Utils.popen_read("#{bin}/grafaman completion zsh")
    (zsh_completion/_grafaman).write output
    prefix.install_metafiles
  end

  test do
    system "#{bin}/grafaman version"
  end
end
