# This file was generated by GoReleaser. DO NOT EDIT.
class Lift < Formula
  desc "Up your service locally."
  homepage "https://github.com/kamilsk/lift"
  version "0.1.1"

  if OS.mac?
    url "https://github.com/kamilsk/lift/releases/download/0.1.1/lift_0.1.1_macOS-64bit.tar.gz"
    sha256 "9733726f072cf7daa44f5fc3af6a5172dbafaf673d22079f31b462c3522b7f31"
  elsif OS.linux?
    url "https://github.com/kamilsk/lift/releases/download/0.1.1/lift_0.1.1_Linux-64bit.tar.gz"
    sha256 "3a87738ab7bfbb902926ee149a3f5b210cb6ab533e673661fbb73dca62feae84"
  end

  def install
    bin.install "lift"
  end

  def caveats; <<~EOS
    Use `eval $(lift up)`
  EOS
  end
end
