# This file was generated by GoReleaser. DO NOT EDIT.
class Retry.Cli < Formula
  desc "CLI tool based on https://github.com/kamilsk/retry package to execute commands with retries."
  homepage "https://github.com/kamilsk/retry.cli"
  url "https://github.com/kamilsk/retry.cli/releases/download/4.0.0/retry_4.0.0_macOS-64bit.tar.gz"
  version "4.0.0"
  sha256 "c0e63496adf53646e05ddabb75e26d894cdc9a7615e8aa50ddbab865ec107aee"

  def install
    bin.install "retry"
  end

  def caveats; <<~EOS
    Use `retry --help` to see detailed help message
  EOS
  end
end
