# This file was generated by GoReleaser. DO NOT EDIT.
class Retry < Formula
  desc "Functional mechanism based on channels to perform actions repetitively until successful."
  homepage "https://github.com/kamilsk/retry"
  url "https://github.com/kamilsk/retry/releases/download/v3.4.3/retry_3.4.3_macOS-64bit.tar.gz"
  version "3.4.3"
  sha256 "89ff6c95bc29d81bcfc5b99e3035d1d5cd96b8bb45b6ec9122b82aeead32b62d"

  def install
    bin.install "retry"
  end

  def caveats; <<~EOS
    Use `retry --help` to see detailed help message
  EOS
  end
end
