# This file was generated by GoReleaser. DO NOT EDIT.
class Semaphore < Formula
  desc "Semaphore pattern implementation with timeout of lock/unlock operations based on channels."
  homepage "https://github.com/kamilsk/semaphore"
  url "https://github.com/kamilsk/semaphore/releases/download/v4.4.0/semaphore_4.4.0_macOS-64bit.tar.gz"
  version "4.4.0"
  sha256 "b50338cce2ab2ab1ea33d56af8ccc976ed7379cf52684a7a931df2cc529f070e"

  def install
    bin.install "semaphore"
  end

  def caveats; <<~EOS
    Use `semaphore help` to see detailed help message
  EOS
  end
end
