# This file was generated by GoReleaser. DO NOT EDIT.
class Semaphore < Formula
  desc "Semaphore pattern implementation with timeout of lock/unlock operations based on channels."
  homepage "https://github.com/kamilsk/semaphore"
  url "https://github.com/kamilsk/semaphore/releases/download/4.3.1/semaphore_4.3.1_macOS-64bit.tar.gz"
  version "4.3.1"
  sha256 "3b8c2206d6581db59240ea7e92ac9a6df5b9118f151921ae28b84b895129a6db"

  def install
    bin.install "semaphore"
  end

  def caveats; <<~EOS
    Use `semaphore help` to see detailed help message
  EOS
  end
end
